# Generated by Django 2.0.5 on 2018-07-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='chapter_pledged',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_chapter',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_position',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='other_info',
            field=models.CharField(blank=True, max_length=560, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year_graduated',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year_pledged',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
