# Generated by Django 2.1 on 2018-11-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='orginization',
            field=models.CharField(blank=True, choices=[('sigma', 'Phi Beta Sigma'), ('zeta', 'Zeta Phi Beta')], max_length=128, null=True),
        ),
    ]
