# Generated by Django 2.0.5 on 2018-07-30 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180730_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_pledged', models.CharField(blank=True, max_length=156, null=True)),
                ('year_pledged', models.IntegerField(blank=True, null=True)),
                ('current_chapter', models.CharField(blank=True, max_length=156, null=True)),
                ('major', models.CharField(blank=True, max_length=256, null=True)),
                ('year_graduated', models.IntegerField(blank=True, null=True)),
                ('current_position', models.CharField(blank=True, max_length=256, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=256, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('other_info', models.CharField(blank=True, max_length=560, null=True)),
                ('business', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='business',
        ),
        migrations.RemoveField(
            model_name='user',
            name='chapter_pledged',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_chapter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='major',
        ),
        migrations.RemoveField(
            model_name='user',
            name='other_info',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='year_graduated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='year_pledged',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
    ]
