# Generated by Django 2.0.5 on 2018-07-30 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180730_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='chapter_pledged',
            new_name='chapters_pledged',
        ),
    ]
