# Generated by Django 2.1 on 2018-11-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181116_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='orginization',
            field=models.CharField(blank=True, choices=[('Phi Beta Sigma', 'Phi Beta Sigma'), ('Zeta Phi Beta', 'Zeta Phi Beta')], max_length=128, null=True),
        ),
    ]
